<template>
    <section class="w-full container mx-auto px-4">
        <ModuleTab title="Our Products" :tabs="tabs"/>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-10 pt-6">
            <ProductCard v-for="product in products" :product-date="product" />
        </div>
    </section>
</template>
<script setup>
const tabs = [
    { name: 'ALL', href: '#', current: false },
    { name: 'NEWEST', href: '#', current: false },
    { name: 'TRENDING', href: '#', current: true },
    { name: 'BEST SELLERS', href: '#', current: false },
    { name: 'FEATURED', href: '#', current: false },
]
const products = [
    {
        id: 1,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '5',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        sales: false,
        salesPrice: '',
    },
    {
        id: 2,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '2',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        sales: false,
        salesPrice: '',
    },
    {
        id: 3,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '3',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        sales: false,
        salesPrice: '',
    },
    {
        id: 4,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '4',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        salesPrice: '',
        sales: false,
    },
    {
        id: 5,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '5',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        salesPrice: '',
        sales: false,
    },
    {
        id: 6,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '2',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        salesPrice: '',
        sales: false,
    },
    {
        id: 7,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '3',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        salesPrice: '',
        sales: false,
    },
    {
        id: 8,
        name: 'Basic Tee',
        href: '#',
        imageSrc: '4',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '$35',
        color: 'Black',
        active: false,
        new: false,
        salesPrice: '',
        sales: false,
    },
]
</script>